name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend_flask:
    name: Backend (Flask)
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Lint Python code
      - name: Lint Python Code
        run: |
          if [ -f .flake8 ] || [ -f setup.cfg ] || [ -f tox.ini ] || [ -f .pep8 ]; then
            flake8 .
          else
            echo "No lint configuration found, skipping linting."
          fi

      # Run Python tests (placeholder)
      - name: Run Python Tests
        run: |
          echo "Running tests..."
          pytest || echo "No tests found."

  deploy:
    name: Deploy & Push to Docker Hub
    needs: [backend_flask]
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - uses: actions/checkout@v3

      # Optional: List repository files to verify docker-compose or Dockerfile exists
      - name: List repository files
        run: ls -al

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend_flask:latest .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend_flask:latest
        #
